[2023-09-21T01:54:27.668+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:54:22.772170+00:00 [queued]>
[2023-09-21T01:54:27.675+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:54:22.772170+00:00 [queued]>
[2023-09-21T01:54:27.675+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T01:54:27.686+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_snowflake> on 2023-09-21 01:54:22.772170+00:00
[2023-09-21T01:54:27.692+0000] {standard_task_runner.py:57} INFO - Started process 2696 to run task
[2023-09-21T01:54:27.695+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_snowflake', 'manual__2023-09-21T01:54:22.772170+00:00', '--job-id', '509', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpae04sru1']
[2023-09-21T01:54:27.697+0000] {standard_task_runner.py:85} INFO - Job 509: Subtask send_to_snowflake
[2023-09-21T01:54:27.733+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:54:22.772170+00:00 [running]> on host fd67d4db30a8
[2023-09-21T01:54:27.797+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T01:54:22.772170+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T01:54:22.772170+00:00'
[2023-09-21T01:54:27.843+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2023-09-21T01:54:27.843+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-09-21T01:54:27.843+0000] {connection.py:1060} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T01:54:27.843+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2023-09-21T01:54:27.924+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T01:54:28.568+0000] {cursor.py:804} INFO - query: [select current_database(), current_schema();]
[2023-09-21T01:54:28.822+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:28.822+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:28.824+0000] {cursor.py:804} INFO - query: [ROLLBACK]
[2023-09-21T01:54:29.075+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:29.076+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:29.077+0000] {cursor.py:804} INFO - query: [CREATE OR REPLACE TABLE student_data( student_id VARCHAR, name VARCHAR, grades_m...]
[2023-09-21T01:54:29.449+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:29.449+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:29.454+0000] {cursor.py:804} INFO - query: [DESC TABLE /* sqlalchemy:_has_object */ student_data]
[2023-09-21T01:54:29.689+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:29.689+0000] {cursor.py:959} INFO - Number of results in first chunk: 7
[2023-09-21T01:54:29.690+0000] {cursor.py:804} INFO - query: [DESC TABLE /* sqlalchemy:_has_object */ student_data]
[2023-09-21T01:54:29.922+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:29.922+0000] {cursor.py:959} INFO - Number of results in first chunk: 7
[2023-09-21T01:54:29.923+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:get_table_names */ TABLES IN student_semantic]
[2023-09-21T01:54:30.176+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:30.177+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:30.178+0000] {cursor.py:804} INFO - query: [select current_database(), current_schema();]
[2023-09-21T01:54:30.400+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:30.400+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:30.402+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:_get_schema_primary_keys */PRIMARY KEYS IN SCHEMA student_sem...]
[2023-09-21T01:54:30.655+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:30.655+0000] {cursor.py:959} INFO - Number of results in first chunk: 0
[2023-09-21T01:54:30.657+0000] {cursor.py:804} INFO - query: [SELECT /* sqlalchemy:_get_schema_columns */ ic.table_name, ic.column_name, ic.da...]
[2023-09-21T01:54:32.753+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:32.753+0000] {cursor.py:959} INFO - Number of results in first chunk: 7
[2023-09-21T01:54:32.754+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:_get_schema_foreign_keys */ IMPORTED KEYS IN SCHEMA student_s...]
[2023-09-21T01:54:33.008+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:33.009+0000] {cursor.py:959} INFO - Number of results in first chunk: 0
[2023-09-21T01:54:33.009+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:_get_schema_unique_constraints */ UNIQUE KEYS IN SCHEMA stude...]
[2023-09-21T01:54:33.276+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:33.276+0000] {cursor.py:959} INFO - Number of results in first chunk: 0
[2023-09-21T01:54:33.277+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:_get_table_comment */ TABLES LIKE 'student_data']
[2023-09-21T01:54:33.516+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:33.516+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:33.517+0000] {cursor.py:804} INFO - query: [DROP TABLE student_data]
[2023-09-21T01:54:33.855+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:33.856+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:33.857+0000] {cursor.py:804} INFO - query: [CREATE TABLE student_data ( student_id TEXT, name TEXT, grades_math BIGINT, grad...]
[2023-09-21T01:54:34.165+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:34.165+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:34.167+0000] {cursor.py:804} INFO - query: [CREATE TEMP STAGE /* Python:snowflake.connector.pandas_tools.write_pandas() */ "...]
[2023-09-21T01:54:34.443+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:34.444+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:34.449+0000] {cursor.py:804} INFO - query: [PUT /* Python:snowflake.connector.pandas_tools.write_pandas() */ 'file:///tmp/tm...]
[2023-09-21T01:54:34.702+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:35.207+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T01:54:35.475+0000] {cursor.py:804} INFO - query: [COPY INTO "STUDENT_DATA" /* Python:snowflake.connector.pandas_tools.write_pandas...]
[2023-09-21T01:54:35.737+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:35.745+0000] {cursor.py:804} INFO - query: [COMMIT]
[2023-09-21T01:54:35.957+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:35.958+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:35.958+0000] {cursor.py:804} INFO - query: [ROLLBACK]
[2023-09-21T01:54:36.161+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:54:36.161+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:54:36.162+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 200, in send_to_snowflake
    df_casted.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/pandas_tools.py", line 499, in pd_writer
    write_pandas(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/pandas_tools.py", line 388, in write_pandas
    copy_results = cursor.execute(copy_into_sql, _is_internal=True).fetchall()
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 908, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01af2121-0001-585f-0000-0002581af1e1: SQL compilation error: error line 1 at position 87
invalid identifier '"student_id"'
[2023-09-21T01:54:36.166+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_snowflake, execution_date=20230921T015422, start_date=20230921T015427, end_date=20230921T015436
[2023-09-21T01:54:36.178+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 509 for task send_to_snowflake (000904 (42000): 01af2121-0001-585f-0000-0002581af1e1: SQL compilation error: error line 1 at position 87
invalid identifier '"student_id"'; 2696)
[2023-09-21T01:54:36.189+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T01:54:36.201+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
