[2023-09-20T19:20:57.048+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.sed_to_processed_lake manual__2023-09-20T19:20:55.941528+00:00 [queued]>
[2023-09-20T19:20:57.056+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.sed_to_processed_lake manual__2023-09-20T19:20:55.941528+00:00 [queued]>
[2023-09-20T19:20:57.056+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T19:20:57.067+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): sed_to_processed_lake> on 2023-09-20 19:20:55.941528+00:00
[2023-09-20T19:20:57.071+0000] {standard_task_runner.py:57} INFO - Started process 258 to run task
[2023-09-20T19:20:57.074+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'sed_to_processed_lake', 'manual__2023-09-20T19:20:55.941528+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmplf5rh626']
[2023-09-20T19:20:57.077+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask sed_to_processed_lake
[2023-09-20T19:20:57.118+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.sed_to_processed_lake manual__2023-09-20T19:20:55.941528+00:00 [running]> on host 6086152831d6
[2023-09-20T19:20:57.412+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='sed_to_processed_lake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T19:20:55.941528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T19:20:55.941528+00:00'
[2023-09-20T19:20:57.413+0000] {logging_mixin.py:151} INFO - entrei na def get_xcom
[2023-09-20T19:20:57.413+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 85, in send_data_to_processed
    df_processed = get_xcom(tasks)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 7, in get_xcom
    return context["ti"].xcom_pull(task_ids=tasks_lists)
KeyError: 'ti'
[2023-09-20T19:20:57.421+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=sed_to_processed_lake, execution_date=20230920T192055, start_date=20230920T192057, end_date=20230920T192057
[2023-09-20T19:20:57.433+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task sed_to_processed_lake ('ti'; 258)
[2023-09-20T19:20:57.449+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T19:20:57.464+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
