[2023-09-20T20:34:55.872+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T20:34:54.352417+00:00 [queued]>
[2023-09-20T20:34:55.880+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T20:34:54.352417+00:00 [queued]>
[2023-09-20T20:34:55.881+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T20:34:55.892+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_missed_days> on 2023-09-20 20:34:54.352417+00:00
[2023-09-20T20:34:55.900+0000] {standard_task_runner.py:57} INFO - Started process 2007 to run task
[2023-09-20T20:34:55.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_missed_days', 'manual__2023-09-20T20:34:54.352417+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmp5op4nc2i']
[2023-09-20T20:34:55.906+0000] {standard_task_runner.py:85} INFO - Job 211: Subtask create_dataframe_missed_days
[2023-09-20T20:34:55.950+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T20:34:54.352417+00:00 [running]> on host 6086152831d6
[2023-09-20T20:34:56.206+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_missed_days' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T20:34:54.352417+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T20:34:54.352417+00:00'
[2023-09-20T20:34:56.216+0000] {logging_mixin.py:151} INFO - json_data None
[2023-09-20T20:34:56.216+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 70, in create_dataframe_missed_days
    df = pd.json_normalize(xcom_pull_obj[key_to_normalize], sep="_")
TypeError: 'NoneType' object is not subscriptable
[2023-09-20T20:34:56.224+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_missed_days, execution_date=20230920T203454, start_date=20230920T203455, end_date=20230920T203456
[2023-09-20T20:34:56.234+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 211 for task create_dataframe_missed_days ('NoneType' object is not subscriptable; 2007)
[2023-09-20T20:34:56.276+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T20:34:56.290+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
