[2023-09-20T19:22:04.012+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.sed_to_processed_lake manual__2023-09-20T19:22:02.734028+00:00 [queued]>
[2023-09-20T19:22:04.020+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.sed_to_processed_lake manual__2023-09-20T19:22:02.734028+00:00 [queued]>
[2023-09-20T19:22:04.020+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T19:22:04.031+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): sed_to_processed_lake> on 2023-09-20 19:22:02.734028+00:00
[2023-09-20T19:22:04.036+0000] {standard_task_runner.py:57} INFO - Started process 284 to run task
[2023-09-20T19:22:04.039+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'sed_to_processed_lake', 'manual__2023-09-20T19:22:02.734028+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmppnbsb_ox']
[2023-09-20T19:22:04.042+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask sed_to_processed_lake
[2023-09-20T19:22:04.084+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.sed_to_processed_lake manual__2023-09-20T19:22:02.734028+00:00 [running]> on host 6086152831d6
[2023-09-20T19:22:04.324+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='sed_to_processed_lake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T19:22:02.734028+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T19:22:02.734028+00:00'
[2023-09-20T19:22:04.325+0000] {logging_mixin.py:151} INFO - entrei na def get_xcom
[2023-09-20T19:22:04.325+0000] {logging_mixin.py:151} INFO - {}
[2023-09-20T19:22:04.326+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 86, in send_data_to_processed
    df_processed = get_xcom(tasks)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 8, in get_xcom
    return context["ti"].xcom_pull(task_ids=tasks_lists)
KeyError: 'ti'
[2023-09-20T19:22:04.332+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=sed_to_processed_lake, execution_date=20230920T192202, start_date=20230920T192204, end_date=20230920T192204
[2023-09-20T19:22:04.343+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task sed_to_processed_lake ('ti'; 284)
[2023-09-20T19:22:04.372+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T19:22:04.399+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
