[2023-09-20T16:55:14.885+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T16:55:13.383725+00:00 [queued]>
[2023-09-20T16:55:14.892+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T16:55:13.383725+00:00 [queued]>
[2023-09-20T16:55:14.892+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T16:55:14.904+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_student> on 2023-09-20 16:55:13.383725+00:00
[2023-09-20T16:55:14.909+0000] {standard_task_runner.py:57} INFO - Started process 895 to run task
[2023-09-20T16:55:14.912+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_student', 'manual__2023-09-20T16:55:13.383725+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmp1w065omn']
[2023-09-20T16:55:14.914+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask create_dataframe_student
[2023-09-20T16:55:14.958+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T16:55:13.383725+00:00 [running]> on host 64864ba3aa5a
[2023-09-20T16:55:15.376+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_student' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T16:55:13.383725+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T16:55:13.383725+00:00'
[2023-09-20T16:55:15.377+0000] {logging_mixin.py:151} INFO - None
[2023-09-20T16:55:15.377+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 21, in create_dataframe
    return pd.json_normalize(json_data[key_to_normalize], sep="_").to_csv(
TypeError: string indices must be integers
[2023-09-20T16:55:15.387+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_student, execution_date=20230920T165513, start_date=20230920T165514, end_date=20230920T165515
[2023-09-20T16:55:15.398+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task create_dataframe_student (string indices must be integers; 895)
[2023-09-20T16:55:15.446+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T16:55:15.459+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
